
# scan server
server:
  addr: 0.0.0.0:8000
  timeout: 30s

datasource:
  redis:
    master: ["redis://redis:6379/0"]
    slave: []

  nodes:
    maxConns: 1
    targets: 
      - address: "192.168.0.80"
        grpc_port: "9090"
        rpc_port: "1317"
    http_proxy_prefix: "/api/nexus/node" 

  hasura:
    target: "hasura:8080"
  postgres:
    host: "postgres_ec_chain"
    port: "5432"
    user: "pguser"
    password: "pgpassword"
    database: "callisto-ec-chain"
    timeout: 30
    maxOpenConns: 30
    maxIdleConns: 30

logger:
  level: debug

trace:
  enable: true
  jaeger_host: jaeger:4317
