chain:
    bech32_prefix: ec
    #请勿改动模块名称
    modules: [
        "modules",
        "message_type",
        "messages",
        "auth",
        "bank",
        "consensus",
        "wasm",
        "upgrade",
        "distribution",
        "feegrant",
        "slashing",
        "staking",
        "gov",
        "sequencer",
        "rollapp",
        "evm",
        "transfer",
        "ante",
        "raw_block",
        "tx_index",
        "settlement",
        "anymsgs"
    ]
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://192.168.0.80:26657
            max_connections: 20
        grpc:
            address: 192.168.0.80:9090
            insecure: true


redis:
  url: "redis://redis:6379/0"


parsing:
    workers: 20
    start_height: 1
    average_block_time: 5s
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
database:
    #固定使用public schema
    url: postgresql://pguser:pgpassword@postgres_ec_chain:5432/callisto-ec-chain?sslmode=disable&search_path=public
    max_open_connections: 50
    max_idle_connections: 50
    partition_size: 1000000
    partition_batch: 1000

logging:
    level: debug
    format: text
